services:
  
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:3.4.1
    ports:
      - "9090:9090"
    volumes:
      - ./configurations/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - prometheus-network
  
  node-exporter:
    container_name: node-exporter
    image: bitnami/node-exporter:1.9.1
    ports:
      - "9100:9100"
    networks:
      - prometheus-network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - prometheus-network

networks:
  prometheus-network:
    driver: bridge

volumes:
  grafana-data: