datadog:
  apiKey: <YOUR_DATADOG_API_KEY>
  site: us5.datadoghq.com
  logs:
    enabled: true
  apm:
    enabled: true
  processAgent:
    enabled: true
  kubelet:
    # host: "host.docker.internal"
    tlsVerify: false
  tags:
    - env:kind

agents:
  containerLogs:
    enabled: true

daemonset:
  useHostPort: true

kubeScheduler:
  enabled: true
  tlsVerify: false
  leaderElection: false

clusterName: kind-dd-monitor  # Must be non-empty and unique per cluster

orchestratorExplorer:
  enabled: true